# Uncomment the next line to define a global platform for your project
platform :osx, '10.10'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'NiconicoPresentationPlayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NiconicoPresentatioPlayer
  pod 'Socket.IO-Client-Swift', '~> 13.3.0'

  target 'NiconicoPresentationPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
